routes/web.php
<?php
use App\Http\Controllers\KontenVideoController;
use App\Http\Controllers\KontenDokumenController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\JobChannelController;
use App\Http\Controllers\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/dosen', function () {
    return view('dosen.index');
})->name('dashboard');
Route::get('/matkul', function () {
    return view('dosen.tugas.index');
})->name('dashboard');
Route::get('/showMatkul', function () {
    return view('dosen.tugas.tambahTugas');
})->name('dashboard');
Route::get('/showUjian', function () {
    return view('dosen.tugas.tambahUjian');
})->name('dashboard');
/*
Route::get('/', function () {
    return view('admin.index');
})->name('dashboard');
Route::get('/form', function () {
    return view('form');
})->name('form');
Route::get('/tab', function () {
    return view('tab');
})->name('form');
*/
// Route::get('/konten-Video', function () {
//     return view('admin.kontenVideo.index');
// })->name('konten-Video');

// Route::get('/konten-dokumen', function () {
//     return view('admin.kontenDokumen.index');
// })->name('konten-dokumen');

// Route::get('/kelas', function () {
//     return view('admin.kelas.index');
// })->name('kelas');
Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('admin.index');
    })->name('dashboard');
    Route::get('/form', function () {
        return view('form');
    })->name('form');
    Route::get('/tab', function () {
        return view('tab');
    })->name('form');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

Route::resource('kontenVideo', KontenVideoController::class);
Route::resource('kontenDokumen', KontenDokumenController::class);
Route::resource('kelas', KelasController::class);
Route::resource('artikel', ArtikelController::class);
Route::resource('iklan', IklanController::class);
Route::resource('profil', ProfilController::class);
Route::resource('jobChannel', JobChannelController::class);
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
    return '<h1>Storage Linked</h1>';
});

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\KontenDokumen;
use App\Models\KontenVideo;

class Kelas extends Model
{
    use HasFactory;
    protected $table = 'kelas';
    protected $fillable = [
        'nama',
        'deskripsi',
    ];

    protected $primaryKey = 'id';

    public function get_dokumen()
    {
    	return $this->hasMany(KontenDokumen::class);
    }

    public function get_video()
    {
    	return $this->hasMany(KontenVideo::class);
    }
}

app/Http/Controllers/API/KelasController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Kelas;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return Kelas::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'deskripsi' => 'required',
        ]);
        return Kelas::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return Kelas::find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $kelas = Kelas::find($id);
        $kelas ->update($request->all());
        return $kelas;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        return Kelas::destroy($id);
    }

    /**
     * Search for a name
     *
     * @param  str  $name
     * @return \Illuminate\Http\Response
     */
    public function search($name)
    {
        return Kelas::where(strtolower('nama'), 'like', '%'.$name.'%')->get();
    }

    public function kelas_dokumen($id)
    {
        return Kelas::find($id)->get_dokumen;
    }


    public function kelas_video($id)
    {
        return Kelas::find($id)->get_video;
    }

}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;
use App\Models\Kelas;
use App\Models\KontenDokumen;
use App\Models\KontenVideo;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $kelas = Kelas::all();
        return view('admin.kelas.index', compact('kelas'));
    }

    public function create()
    {
        return view('admin.kelas.tambah');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'deskripsi' => 'required',
        ]);
        Kelas::create([
            'nama' => $request->nama,
            'deskripsi' => $request->deskripsi,
        ]);
        //notify()->success('Kelas berhasil ditambahkan!');
        return redirect()->route('kelas.index')
            ->with('success', 'Kelas Berhasil Ditambahkan');
    }

    public function show($id)
    {
        $kelas = Kelas::where('id', $id)->first();
        $kontenDokumen = kontenDokumen::where('kelas_id', $id)->get();
        $kontenVideo = kontenVideo::where('kelas_id', $id)->get();
        $kelasselect = Kelas::all();
        // dd($kontenVideo);
        return view('admin.kelas.show', compact('kelas','kontenDokumen','kontenVideo','kelasselect'));
    }


    public function edit($id)
    {
        $kelas = Kelas::find($id);
 
        return view('admin.kelas.edit', compact('kelas'));
    }

    public function update(Request $request, $id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->nama = $request->nama;
        $kelas->deskripsi = $request->deskripsi;
        $kelas->save();
        //notify()->success('Kelas berhasil diedit!');
        return redirect()->route('kelas.index')
        ->with('edit', 'Kelas Berhasil Diedit');
    }

    public function destroy($id)
    {
        Kelas::where('id', $id)->delete();
        //notify()->success('Kelas berhasil dihapus!');
        return redirect()->route('kelas.index')
            ->with('delete', 'Kelas Berhasil Dihapus');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/kelas/edit.blade.php
<x-app-layout>
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-5 col-12 mx-auto">
        <div class="card card-body mt-4">
          <h6 class="mb-0">Edit Kelas</h6>
          <hr class="horizontal dark my-3">
          <div class="card-body">
            <form role="form text-left" action="{{route('kelas.update',$kelas->id)}}" method="POST" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Nama Kelas</label>
                <input type="text" class="form-control" name="nama" placeholder="Nama" value="{{$kelas->nama}}" aria-label="Name" aria-describedby="email-addon" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Deskripsi Kelas</label>
                <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi Kelas" value="{{$kelas->deskripsi}}" aria-label="Name" aria-describedby="email-addon" required>
              </div>
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {{-- @push('scripts')
  <script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      toolbar_mode: 'floating',
   });
  </script>
  @endpush --}}

</x-app-layout>

resources/views/admin/kelas/index.blade.php
<x-app-layout>
  <div class="col-md-12 mb-lg-0 mb-4">
    <div class="card mt-4">
      <div class="card-header pb-0 p-3">
        <div class="row">
          <div class="col-6 d-flex align-items-center">
            <h6 class="mb-0">Data Kelas</h6>
          </div>
          <div class="col-6 text-end">
            <a class="btn bg-gradient-dark mb-0" href="{{route('kelas.create')}}"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah Data</a>
          </div>
        </div>
      </div>
      <div class="card-body  px-0 pt-0 pb-2">

        <table id="datatable-search" class="table align-items-center mb-0">

          <thead>
            <tr>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">No</th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nama</th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Deskripsi</th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Aksi</th>
            </tr>
          </thead>

          <tbody>
            @foreach ($kelas as $item)
            <tr>
              <td class="align-middle text-center">
                <span class="text-secondary text-xs font-weight-bold">{{ $loop->iteration }}</span>
              </td>
              <td class="align-middle text-center">
                <p class="text-xs font-weight-bold mb-0">{{ $item->nama }}</p>
              </td>
              <td class="align-middle text-center">
                <span class="text-secondary text-xs font-weight-bold">{!! $item->deskripsi !!}</span>
              </td>
              <td>
                <div class="ms-auto text-center">
                  <form action="{{route('kelas.destroy', $item->id)}}" method="POST" style="display: inline">
                    @csrf
                    @method("DELETE")
                    <button type="submit" class="btn btn-link text-danger text-gradient px-3 mb-0 show_confirm" data-toggle="tooltip" title='Delete'><i class="fas fa-trash text-secondary"></i></button>
                  </form>
                  <a class="btn btn-link text-dark px-3 mb-0" href="{{route('kelas.edit', $item->id)}}"><i class="fas fa-user-edit text-secondary"></i></a>
                  <a class="btn btn-link text-dark px-3 mb-0" href="{{route('kelas.show', $item->id)}}"><i class="fas fa-eye text-secondary"></i></a>
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>

  @push('scripts')
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });

    
    $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Hapus Data?`,
                text: "Jika data terhapus, data akan hilang selamanya!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                form.submit();
              }
            });
        });
    
  </script>
  @endpush
</x-app-layout>

resources/views/admin/kelas/show.blade.php
<x-app-layout>
  <div class="row">
    <div class="col-6">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <h3 class="text-center">Detail {{$kelas->nama}}</h3>
        </div>
        <div class="row px-xl-5 px-sm-4 px-3">

          <div class="card-body">
            <div class="mb-3">
              <label for="exampleFormControlSelect1">Nama Kelas</label>
              <input type="text" class="form-control" name="nama" placeholder="Nama" value="{{$kelas->nama}}" readonly>
            </div>
            <div class="mb-3">
              <label for="exampleFormControlSelect1" >Deskripsi</label>
              <textarea class="form-control" aria-label="With textarea" name="deskripsi" rows="4">{{$kelas->deskripsi}}</textarea>
          </div>
            <div class="row">
              <div class="col-md-6">
                <div class="card">
                  <div class="card-header mx-4 p-3 text-center">
                    <div class="icon icon-shape icon-lg bg-gradient-primary shadow text-center border-radius-lg">
                      <i class="fas fa-landmark opacity-10"></i>
                    </div>
                  </div>
                  <div class="card-body pt-0 p-3 ">
                    <h6 class="text-center mb-0">Konten Video</h6>
                    {{-- <span class="text-xs">
                      
                    </span> --}}
                    <hr class="horizontal dark my-3">
                    <h5 class="mb-0">
                      @foreach ($kontenVideo as $item)
                      <li>{{$item->judul}}</li>
                      @endforeach
                    </h5>
                  </div>
                </div>
              </div>
              <div class="col-md-6 mt-md-0 mt-4">
                <div class="card">
                  <div class="card-header mx-4 p-3 text-center">
                    <div class="icon icon-shape icon-lg bg-gradient-primary shadow text-center border-radius-lg">
                      <i class="fab fa-paypal opacity-10"></i>
                    </div>
                  </div>
                  <div class="card-body pt-0 p-3 ">
                    <h6 class="text-center mb-0">Konten Dokumen</h6>
                    <hr class="horizontal dark my-3">
                    <h5 class="mb-0">
                      @foreach ($kontenDokumen as $item)
                      <li>{{$item->judul}}</li>
                      @endforeach
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {{-- BLABLA --}}
    <div class="col-md-6 ">
      {{-- <div class="col-xl-12"> --}}
      <div class="card">
        <div class="card-header d-flex pb-0 p-3">
          <h6 class="my-auto">Tambah Data</h6>
          <div class="nav-wrapper position-relative ms-auto w-50">
            <ul class="nav nav-pills nav-fill p-1" role="tablist">
              <li class="nav-item">
                <a class="nav-link mb-0 px-0 py-1 active" data-bs-toggle="tab" href="#cam1" role="tab" aria-controls="cam1" aria-selected="true">
                  Konten Video
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link mb-0 px-0 py-1" data-bs-toggle="tab" href="#cam2" role="tab" aria-controls="cam2" aria-selected="false">
                  Konten Dokumen
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="card-body p-3 mt-2">
          <div class="tab-content" id="v-pills-tabContent">
            {{-- <div class="" style="background-image: url('../../assets/img/bg-smart-home-1.jpg'); background-size:cover;"> --}}
            <div class="card-body tab-pane fade show position-relative active  border-radius-lg" id="cam1" role="tabpanel" aria-labelledby="cam1">
              <form role="form text-left" action="{{route('kontenVideo.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Judul</label>
                  <input type="text" class="form-control" name="judul" placeholder="Masukkan Judul" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlSelect1">Deskripsi</label>
                    <textarea class="form-control" aria-label="With textarea" name="deskripsi" rows="4" required></textarea>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Kategori</label>
                  <select class="form-control" name="kategori" id="exampleFormControlSelect1" required>
                    <option value="Basic">Basic</option>
                    <option value="Intermediate">Intermediate</option>
                    <option value="Advanced">Advanced</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Link</label>
                  <input type="text" class="form-control" name="link" placeholder="Masukkan Link" required>
                </div>

                <div class="mb-3">
                  <label for="exampleFormControlSelect1">BAB</label>
                  <input type="number" class="form-control" name="bab" required>
                </div>

                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Kelas</label>
                  <select class="form-control" id="exampleFormControlSelect1" disabled>
                    @foreach ($kelasselect as $item)
                    <option value="{{$item->id}}" @if ($item->id == $kelas->id)
                      selected
                      @endif>{{$item->nama}}</option>
                    @endforeach
                  </select>
                  <input name="kelas_id" value="{{$kelas->id}}" type="hidden" required>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Tambah</button>
                </div>
              </form>
            </div>

            <div class="card-body tab-pane fade position-relative  border-radius-lg" id="cam2" role="tabpanel" aria-labelledby="cam2">
              <form role="form text-left" action="{{route('kontenDokumen.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Judul</label>
                  <input type="text" class="form-control" name="judul" placeholder="Masukkan Judul" required>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Deskripsi</label>
                  <textarea class="form-control" aria-label="With textarea" name="deskripsi" rows="4" required></textarea>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Kategori</label>
                  <select class="form-control" name="kategori" id="exampleFormControlSelect1" required>
                    <option value="Basic">Basic</option>
                    <option value="Intermediate">Intermediate</option>
                    <option value="Advanced">Advanced</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">File Dokumen</label>
                  <input type="file" class="form-control" name="file" required>
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlSelect1">BAB</label>
                  <input type="number" class="form-control" name="bab" required>
                </div>

                <div class="mb-3">
                  <label for="exampleFormControlSelect1">Kelas</label>
                  <select class="form-control" id="exampleFormControlSelect1" disabled>
                    @foreach ($kelasselect as $item)
                    <option value="{{$item->id}}" @if ($item->id == $kelas->id)
                      selected
                      @endif>{{$item->nama}}</option>
                    @endforeach
                  </select>
                  <input name="kelas_id" value="{{$kelas->id}}" type="hidden" required>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Tambah</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  {{-- @push('scripts')
  <script>
    tinymce.init({
      selector: ".nonEditableMCE",
      plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      toolbar_mode: 'floating',
      readonly: 1
    });

    tinymce.init({
      selector: ".editableMCE",
      plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      toolbar_mode: 'floating',

    });
  </script>
  @endpush --}}

</x-app-layout>

resources/views/admin/kelas/tambah.blade.php
<x-app-layout> 
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-5 mx-auto">
        <div class="card card-body mt-4">
          <h6 class="mb-0">Tambah Data Kelas</h6>
          <hr class="horizontal dark my-3">
          <div class="card-body">
            <form role="form text-left" action="{{route('kelas.store')}}" method="POST">
              @csrf
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Nama Kelas</label>
                <input type="text" class="form-control" name="nama" placeholder="Nama" aria-label="Name" aria-describedby="email-addon" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Deskripsi</label>
                <textarea class="form-control" aria-label="With textarea" name="deskripsi" rows="4" required></textarea>
              </div>
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>                
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {{-- @push('scripts')
  <script>
    tinymce.init({
      selector: 'textarea',
      plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
      toolbar_mode: 'floating',
   });
  </script>
  @endpush --}}
</x-app-layout>