routes/web.php
<?php
use App\Http\Controllers\KontenVideoController;
use App\Http\Controllers\KontenDokumenController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\JobChannelController;
use App\Http\Controllers\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/dosen', function () {
    return view('dosen.index');
})->name('dashboard');
Route::get('/matkul', function () {
    return view('dosen.tugas.index');
})->name('dashboard');
Route::get('/showMatkul', function () {
    return view('dosen.tugas.tambahTugas');
})->name('dashboard');
Route::get('/showUjian', function () {
    return view('dosen.tugas.tambahUjian');
})->name('dashboard');
/*
Route::get('/', function () {
    return view('admin.index');
})->name('dashboard');
Route::get('/form', function () {
    return view('form');
})->name('form');
Route::get('/tab', function () {
    return view('tab');
})->name('form');
*/
// Route::get('/konten-Video', function () {
//     return view('admin.kontenVideo.index');
// })->name('konten-Video');

// Route::get('/konten-dokumen', function () {
//     return view('admin.kontenDokumen.index');
// })->name('konten-dokumen');

// Route::get('/kelas', function () {
//     return view('admin.kelas.index');
// })->name('kelas');
Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('admin.index');
    })->name('dashboard');
    Route::get('/form', function () {
        return view('form');
    })->name('form');
    Route::get('/tab', function () {
        return view('tab');
    })->name('form');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

Route::resource('kontenVideo', KontenVideoController::class);
Route::resource('kontenDokumen', KontenDokumenController::class);
Route::resource('kelas', KelasController::class);
Route::resource('artikel', ArtikelController::class);
Route::resource('iklan', IklanController::class);
Route::resource('profil', ProfilController::class);
Route::resource('jobChannel', JobChannelController::class);
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
    return '<h1>Storage Linked</h1>';
});

app/Models/JobChannel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JobChannel extends Model
{
    use HasFactory;
    protected $table = 'job_channel';
    protected $fillable = [
        'posisi_pekerjaan',
        'nama_perusahaan',
        'gaji',
        'bidang',
        'tipe',
        'pengalaman',
        'foto',
    ];

    protected $primaryKey = 'id';
}

app/Http/Controllers/API/JobChannelController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Models\JobChannel;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class JobChannelController extends Controller
{
    public function index()
    {
        $jobChannel = JobChannel::all();
        return response()->json([
            "message" => "success",
            "data" => $jobChannel
        ], 200);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),
              [
                'posisi_pekerjaan' => 'required',
                'nama_perusahaan' => 'required',
                'gaji' => 'required',
                'bidang' => 'required',
                'tipe' => 'required',
                'pengalaman' => 'required',
                'foto' => 'required',
             ]);
        if ($validator->fails()) {
            return response()->json(['error'=>$validator->errors()], 401);
        }

        if ($files = $request->file('foto')) {

            //store file into document folder
            $extention = $request->foto->extension();
            $file_name = time().'.'.$extention;
            $txt = 'storage/job-channel/'. $file_name;
            $request->foto->storeAs('public/job-channel', $file_name);

            //store your file into database
            $jobChannel = new JobChannel();
            $jobChannel->posisi_pekerjaan = $request->posisi_pekerjaan;
            $jobChannel->nama_perusahaan = $request->nama_perusahaan;
            $jobChannel->gaji = $request->gaji;
            $jobChannel->bidang = $request->bidang;
            $jobChannel->tipe = $request->tipe;
            $jobChannel->pengalaman = $request->pengalaman;
            $jobChannel->foto = $file_name;
            $jobChannel->save();

            return response()->json([
                "success" => true,
                "message" => "Images successfully uploaded",
                "file" => $txt
            ]);

        }
        return JobChannel::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return JobChannel::find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $jobChannel = JobChannel::find($id);
        $jobChannel ->update($request->all());
        return $jobChannel;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        return JobChannel::destroy($id);
    }

    public function download($id)
    {
        $jobChannel = JobChannel::find($id);
        $lst = explode('/', $jobChannel->foto);
        $txt = 'api/view2/'.$lst[2];
        return redirect($txt);
    }

    public function view($id)
    {
        $jobChannel = JobChannel::find($id);
        $lst = explode('/', $jobChannel->foto);
        //$txt = 'api/view2/'.$lst[0];
        $filename = $lst[2];
        $txt = '/storage/job-channel/'. $filename;
        return redirect($txt);
    }


}

app/Http/Controllers/JobChannelController.php
<?php

namespace App\Http\Controllers;
use App\Models\JobChannel;
use Illuminate\Http\Request;

class JobChannelController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $jobChannel = JobChannel::all();
        return view('admin.jobChannel.index', compact('jobChannel'));
    }

    public function create()
    {
        return view('admin.jobChannel.tambah');
    }

    public function store(Request $request)
    {
        $request->validate([
            'posisi_pekerjaan' => 'required',
            'nama_perusahaan' => 'required',
            'gaji' => 'required',
            'bidang' => 'required',
            'tipe' => 'required',
            'pengalaman' => 'required',
            'foto' => 'required',
        ]);
        $upload = $request->foto;
        if (isset($request->foto)) {
            $extention = $request->foto->extension();
            $file_name = time() . '.' . $extention;
            $txt = "storage/job-channel/". $file_name;
            $request->foto->storeAs('public/job-channel', $file_name);
        } else {
            $file_name = null;
        }
        JobChannel::create([
            'posisi_pekerjaan' => $request->posisi_pekerjaan,
            'nama_perusahaan' => $request->nama_perusahaan,
            'gaji' => $request->gaji,
            'bidang' => $request->bidang,
            'tipe' => $request->tipe,
            'pengalaman' => $request->pengalaman,
            'foto' => $file_name,

        ]);
        //notify()->success('Job Channel berhasil ditambahkan!');
        return redirect()->route('jobChannel.index')
            ->with('success', 'Job Channel Berhasil Ditambahkan');
    }

    public function show($id)
    {
        $jobChannel = JobChannel::where('id', $id)->first();
        // dd($kontenVideo);
        return view('admin.jobChannel.show', compact('jobChannel'));
    }


    public function edit($id)
    {
        $jobChannel = JobChannel::find($id);
 
        return view('admin.jobChannel.edit', compact('jobChannel'));
    }

    public function update(Request $request, $id)
    {
        $jobChannel = JobChannel::findOrFail($id);
        $jobChannel->posisi_pekerjaan = $request->posisi_pekerjaan;
        $jobChannel->nama_perusahaan = $request->nama_perusahaan;
        $jobChannel->gaji = $request->gaji;
        $jobChannel->bidang = $request->bidang;
        $jobChannel->tipe = $request->tipe;
        $jobChannel->pengalaman = $request->pengalaman;

        if (isset($request->foto)){
            $extention = $request->foto->extension();
            $file_name = time().'.'.$extention;
            $txt = "storage/job-channel/". $file_name;
            $request->foto->storeAs('public/job-channel', $file_name);
            $jobChannel->foto = $txt;
        }else{}
        $jobChannel->save();
        //notify()->success('Job Channel berhasil diedit!');
        return redirect()->route('jobChannel.index')
        ->with('edit', 'Job Channel Berhasil Diedit');
    }

    public function destroy($id)
    {
        JobChannel::where('id', $id)->delete();
        //notify()->success('Job Channel berhasil dihapus!');
        return redirect()->route('jobChannel.index')
            ->with('delete', 'Job Channel Berhasil Dihapus');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/jobChannel/edit.blade.php
<x-app-layout>
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-6 col-12 mx-auto">
        <div class="card card-body mt-4">
          <h6 class="mb-0">Edit Job Channel</h6>
          <hr class="horizontal dark my-3">
          <div class="card-body">
            <form role="form text-left" action="{{route('jobChannel.update',$jobChannel->id)}}" method="POST" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Posisi Pekerjaan</label>
                <input type="text" class="form-control" name="posisi_pekerjaan" value="{{$jobChannel->posisi_pekerjaan}}" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Nama Perusahaan</label>
                <input type="text" class="form-control" name="nama_perusahaan" value="{{$jobChannel->nama_perusahaan}}" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Gaji</label>
                <input type="number" class="form-control" name="gaji" value="{{$jobChannel->gaji}}" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Bidang</label>
                <input type="text" class="form-control" name="bidang" value="{{$jobChannel->bidang}}" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Tipe</label>
                <select class="form-control" name="tipe">
                  <option disabled selected>{{$jobChannel->tipe}}</option>
                  <option value="Full Time">Full Time</option>
                  <option value="Internship">Internship</option>
                  <option value="Part Time">Part Time</option>
                </select>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Pengalaman</label>
                <input type="text" class="form-control" name="pengalaman" value="{{$jobChannel->pengalaman}}" required>
              </div>        
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Foto</label> <br>
                <img src="{{ asset( $jobChannel->foto) }}" alt=""> <br>
                <input type="file" class="form-control" name="foto" value="{{$jobChannel->foto}}" required>
              </div>         
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/admin/jobChannel/index.blade.php
<x-app-layout>
  <div class="col-md-12 mb-lg-0 mb-4">
    <div class="card mt-4">
      <div class="card-header pb-0 p-3">
        <div class="row">
          <div class="col-6 d-flex align-items-center">
            <h6 class="mb-0">Data Job Channel</h6>
          </div>
          <div class="col-6 text-end">
            <a class="btn bg-gradient-dark mb-0" href="{{route('jobChannel.create')}}"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah Data</a>
          </div>
        </div>
      </div>
      <div class="card-body p-3">
        <div class="row">
          <div class="table-responsive p-0">
            <table id="datatable-search" class="table align-items-center mb-0">

              <thead>
                <tr>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">No</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ">Posisi Pekerjaan</th>
                  <th class="text-center text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nama Perusahaan</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Gaji</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Bidang</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Tipe</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Pengalaman</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Foto</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Aksi</th>
                </tr>
              </thead>

              <tbody>
                @foreach ($jobChannel as $item)
                <tr>
                  <td class="align-middle text-center">
                    <span class="text-secondary text-xs font-weight-bold">{{ $loop->iteration }}</span>
                  </td>
                  <td class="align-middle text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->posisi_pekerjaan }}</p>
                  </td>
                  <td class="align-middle text-center">
                    <span class="text-secondary text-xs font-weight-bold">{{ $item->nama_perusahaan }}</span>
                  </td>
                  <td class="align-middle text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->gaji }}</p>
                  </td>
                  <td class="align-middle text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->bidang }}</p>
                  </td>
                  <td class="align-middle text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->tipe }}</p>
                  </td>
                  <td class="align-middle text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->pengalaman }}</p>
                  </td>
                  <td class="align-middle text-center">
                    <img src="{{asset('storage/job-channel/'.$item->foto)}}" width="100"  >
                  </td>
                  <td>
                    <div class="ms-auto text-center">
                      <form action="{{route('jobChannel.destroy', $item->id)}}" method="POST" style="display: inline">
                        @csrf
                        @method("DELETE")
                        <button type="submit" class="btn btn-link text-danger text-gradient px-3 mb-0 show_confirm" data-toggle="tooltip" title='Delete'><i class="fas fa-trash text-secondary"></i></button>
                      </form>
                      <a class="btn btn-link text-dark px-3 mb-0" href="{{route('jobChannel.edit', $item->id)}}"><i class="fas fa-user-edit text-secondary"></i></a>
                    </div>
                  </td>
                </tr>
                {{-- <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $item->nama }}</td>
                  <td>{!! $item->deskripsi !!}</td>
                  <td>
                    <div class="btn-group" role="group">
                      <a href="{{route('kelas.edit', $item->id)}}" class="btn btn-primary"><i class="material-icons">edit</i></a>
                      <form action="{{route('kelas.destroy', $item->id)}}" method="POST">
                        @csrf
                        @method("DELETE")
                        <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                      </form>
                    </div>
                  </td>
                </tr> --}}
                @endforeach
              </tbody>

            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  @push('scripts')
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });

    
    $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Hapus Data?`,
                text: "Jika data terhapus, data akan hilang selamanya!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                form.submit();
              }
            });
        });
    
  </script>
  @endpush
</x-app-layout>

resources/views/admin/jobChannel/show.blade.php
<x-app-layout>
  <div class="row">
    <div class="col-6">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <h3 class="text-center">Detail {{$kelas->nama}}</h3>
        </div>
        <div class="row px-xl-5 px-sm-4 px-3">

          <div class="card-body">
            <div class="mb-3">
              <label for="exampleFormControlSelect1">Nama Kelas</label>
              <input type="text" class="form-control" name="nama" placeholder="Nama" value="{{$kelas->nama}}" readonly>
            </div>
            <div class="mb-3">
              <label for="exampleFormControlSelect1">Deskripsi Kelas</label>
              <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi" value="{{$kelas->deskripsi}}" readonly>
            </div>
            <div class="mb-3" >

              <table>
                <thead>
                  <th class="text-left"> Konten Video </th>
                  <th> Konten Dokumen </th>
                </thead>
                <tbody>
                  <tr>
                    <td class="text-right">
                      <ul>
                        @foreach ($kontenVideo as $item)
                        <li>{{$item->judul}}</li>
                        @endforeach
                      </ul>
                    </td>
                    <td>
                      <ul>
                        @foreach ($kontenDokumen as $item)
                        <li>{{$item->judul}}</li>
                        @endforeach
                      </ul>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/admin/jobChannel/tambah.blade.php
<x-app-layout>
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-6 col-12 mx-auto">
        <div class="card card-body mt-4">
          <h6 class="mb-0">Tambah Job Channel</h6>
          <hr class="horizontal dark my-3">
          <div class="card-body">
            <form role="form text-left" action="{{route('jobChannel.store')}}" method="POST"  enctype="multipart/form-data">
              @csrf
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Posisi Pekerjaan</label>
                <input type="text" class="form-control" name="posisi_pekerjaan" placeholder="Posisi Pekerjaan" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Nama Perusahaan</label>
                <input type="text" class="form-control" name="nama_perusahaan" placeholder="Nama Perusahaan" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Gaji</label>
                <input type="number" class="form-control" name="gaji" placeholder="Gaji" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Bidang</label>
                <input type="text" class="form-control" name="bidang" placeholder="Bidang" required>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Tipe</label>
                <select class="form-control" name="tipe" id="exampleFormControlSelect1" required>
                  <option value="Full Time">Full Time</option>
                  <option value="Intersship">Internship</option>
                  <option value="Part Time">Part Time</option>
                </select>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Pengalaman</label>
                <input type="text" class="form-control" name="pengalaman" placeholder="Pengalaman" required>
              </div>        
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Foto</label>
                <input type="file" class="form-control" name="foto" required>
              </div>               
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>